name: Generate binaries
on:
  release:
    types:
      - created
permissions:
  contents: write
jobs:
  binaries:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.18
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Fetch repo
        run: git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: v1.21.x
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}